name: CI pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 26

      - name: Install dependencies
        uses: npm install

      - name: Run tests
        uses: npm run test
